version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: painelml-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: painelml
      POSTGRES_PASSWORD: dev_password_123
      POSTGRES_DB: painelml
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U painelml"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
