version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: painelml-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: painelml
      POSTGRES_PASSWORD: dev_password_123
      POSTGRES_DB: painelml
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U painelml"]
      interval: 10s
      timeout: 5s
      retries: 5

  localstack:
    image: localstack/localstack:3.0
    container_name: painelml-localstack
    restart: unless-stopped
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs
      - DEBUG=0
      - PERSISTENCE=0
      - EAGER_SERVICE_LOADING=1
    volumes:
      - localstack_data:/var/lib/localstack
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  postgres_data:
  localstack_data:
